blank_issues_enabled: false
contact_links:
  - name: Open-ended question or discussion
    url: https://github.com/jpgomesr/netchaos/discussions
    about: For anything that doesn't fit one of the issue forms.
